name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npx ionic build --prod --release 
    - uses: actions/upload-artifact@v3 
      with:
        name: frontend-build
        path: frontend/www

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TELEFOOD_4EE40 }}
        projectId: telefood-4ee40
        channelId: "preview"
        ignoreFile: true

        build: ${{ github.workspace }}/frontend-build  
