name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npx ionic build --prod --release
    - uses: actions/upload-artifact@v3 
      with:
        name: frontend-build 
        path: frontend/www 

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TELEFOOD_4EE40 }}
        channelId: live
        projectId: telefood-4ee40
        build: ${{ github.workspace }}/frontend-build  
